<?php

namespace AppBundle\Entity\Compta;

use Doctrine\ORM\EntityRepository;

/**
 * AccompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccompteRepository extends EntityRepository
{
	public function findForCompany($company){
		$qb = $this->createQueryBuilder('a')
		->leftJoin('AppBundle\Entity\CRM\DocumentPrix', 'd', 'WITH', 'd.id = a.devis')
		->leftJoin('AppBundle\Entity\CRM\Compte', 'c', 'WITH', 'c.id = d.compte')
		->where('c.company = :company')
		->setParameter('company', $company);
	
		return $qb->getQuery()->getResult();
	}
}
