<?php

namespace AppBundle\Entity\Compta;

use Doctrine\ORM\EntityRepository;

/**
 * RemiseChequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemiseChequeRepository extends EntityRepository
{
	public function findForCompany($company){
		$qb = $this->createQueryBuilder('r')
		->leftJoin('AppBundle\Entity\Compta\CompteBancaire', 'c', 'WITH', 'c.id = r.compteBancaire')
		->where('c.company = :company')
		->setParameter('company', $company);

		return $qb->getQuery()->getResult();
	}
	
	public function count($company){
		$result = $this->createQueryBuilder('r')
		->select('COUNT(r)')
		->leftJoin('AppBundle\Entity\Compta\CompteBancaire', 'c', 'WITH', 'c.id = r.compteBancaire')
		->where('c.company = :company')
		->setParameter('company', $company)
		->getQuery()
		->getSingleScalarResult();
	
		return $result;
	}
	
	public function findForList($company, $length, $start, $orderBy, $dir, $search){
		$qb = $this->createQueryBuilder('r')
		->select('r.id', 'r.date', 'r.num')
		->leftJoin('AppBundle\Entity\Compta\CompteBancaire', 'c', 'WITH', 'c.id = r.compteBancaire')
		->where('c.company = :company')
		->setParameter('company', $company);
	
		$qb->setMaxResults($length)
		->setFirstResult($start)
		->addOrderBy('r.'.$orderBy, $dir);
	
		return $qb->getQuery()->getResult();
	}
	
	public function countForList($company, $search){
		$qb = $this->createQueryBuilder('r')
		->select('COUNT(r)')
		->leftJoin('AppBundle\Entity\Compta\CompteBancaire', 'c', 'WITH', 'c.id = r.compteBancaire')
		->where('c.company = :company')
		->setParameter('company', $company);
	
		if($search != ""){
	
		}
	
		return $qb->getQuery()->getSingleScalarResult();
	}
}
