<?php

namespace AppBundle\Entity\Compta;

use Doctrine\ORM\EntityRepository;

/**
 * SoldeCompteBancaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldeCompteBancaireRepository extends EntityRepository
{
	public function findLatest($compteBancaire){
		$qb = $this->createQueryBuilder('s')
		->where('s.compteBancaire = :compteBancaire')
		->setParameter('compteBancaire', $compteBancaire)
		->orderBy('s.date', 'DESC')
		->setMaxResults(1);
	
		return $qb->getQuery()->getSingleResult();
	}
}
