# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    appbundle.utils_service:
        class: AppBundle\Service\UtilsService
        calls:
            - [setContainer, ["@service_container"]]
    appbundle.maileva_service:
        class: AppBundle\Service\MailevaService
        calls:
            - [setContainer, ["@service_container"]]
    appbundle.receiptbank_service:
        class: AppBundle\Service\ReceiptBankService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [@buzz]
    appbundle.activation_outils:
        class: AppBundle\Service\ActivationOutilsService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager ]
    appbundle.num_service:
        class: AppBundle\Service\NumService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager ]
    appbundle.chart_service:
        class: AppBundle\Service\ChartService
        calls:
            - [setContainer, ["@service_container"]]
    appbundle_user.registration.form.type:
        class: AppBundle\Form\User\RegistrationFormType
        tags:
            - { name: form.type, alias: appbundle_user_registration }
    appbundle.crm_opportunite_service:
        class: AppBundle\Service\CRM\OpportuniteService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager ]
    appbundle.crm_prospection_service:
        class: AppBundle\Service\CRM\ProspectionService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager ]
    appbundle.compta_depense_service:
        class: AppBundle\Service\Compta\DepenseService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager ]
    appbundle.compta_journal_ventes_controller:
        class: AppBundle\Controller\Compta\JournalVentesController
        calls:
            - [setContainer, ["@service_container"]]
    appbundle.compta_journal_banque_controller:
        class: AppBundle\Controller\Compta\JournalBanqueController
        calls:
            - [setContainer, ["@service_container"]]
    appbundle.compta_journal_achats_controller:
        class: AppBundle\Controller\Compta\JournalAchatsController
        calls:
            - [setContainer, ["@service_container"]]
    appbundle.compta_compte_comptable_controller:
        class: AppBundle\Controller\Compta\CompteComptableController
        calls:
            - [setContainer, ["@service_container"]]
    appbundle.compta_operation_diverse_service:
          class: AppBundle\Service\Compta\OperationDiverseService
          calls:
              - [setContainer, ["@service_container"]]
          arguments: [ @doctrine.orm.entity_manager, @appbundle.compta_compte_comptable_service ]
    appbundle.compta_compte_comptable_service:
        class: AppBundle\Service\Compta\CompteComptableService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager ]
    appbundle.compta_tableau_tresorerie_service:
        class: AppBundle\Service\Compta\TableauTresorerieService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager, @appbundle.utils_service ]
    appbundle.compta_tableau_bord_service:
        class: AppBundle\Service\Compta\TableauBordService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager, @appbundle.utils_service, @phpexcel ]

    appbundle.compta_balance_generale_service:
        class: AppBundle\Service\Compta\BalanceGeneraleService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager ]
    appbundle.compta_tableau_tva_service:
        class: AppBundle\Service\Compta\TableauTVAService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager ]
    appbundle.compta_grand_livre_service:
        class: AppBundle\Service\Compta\GrandLivreService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager ]
    appbundle.prospection:
        class: AppBundle\Service\CRM\ProspectionService
        calls:
            - [setContainer, ["@service_container"]]
        arguments: [ @doctrine.orm.entity_manager ]
    mautic:
        class: AppBundle\Service\mautic\MauticApiService
        arguments: ["@session", %mautic_api_url%]