<?php

namespace AppBundle\Entity\CRM;

use Doctrine\ORM\EntityRepository;

/**
 * OpportuniteSousTraitanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportuniteSousTraitanceRepository extends EntityRepository
{
  public function findForCompanyByYear($company, $year){

    $qb = $this->createQueryBuilder('s')
      ->innerJoin('s.opportunite', 'o')
      ->innerJoin('o.compte', 'c')
      ->where('c.company = :company')
      ->andWhere('o.dateCreation >= :start')
      ->andWhere('o.dateCreation <= :end')
      ->setParameter('company', $company)
      ->setParameter('start', $year.'-01-01')
      ->setParameter('end',  $year.'-12-31');

    return $qb->getQuery()->getResult();
  }

  public function findForCompany($company){

    $qb = $this->createQueryBuilder('s')
      ->innerJoin('s.opportunite', 'o')
      ->innerJoin('o.compte', 'c')
      ->where('c.company = :company')
      ->setParameter('company', $company);

    return $qb->getQuery()->getResult();
  }

  public function findHavingDepense($depense){
     $qb = $this->createQueryBuilder('s')
      ->leftJoin('s.depenses', 'd')
      ->where('d.id = :depense')
      ->setParameter('depense', $depense);

    return $qb->getQuery()->getResult();
  }
}
