<?php

namespace AppBundle\Entity\CRM;

use Doctrine\ORM\EntityRepository;

/**
 * OpportuniteRepartitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportuniteRepartitionRepository extends EntityRepository
{
  public function findForCompanyByYear($company, $year){

    $qb = $this->createQueryBuilder('r')
      ->innerJoin('r.opportunite', 'o')
      ->innerJoin('o.compte', 'c')
      ->where('c.company = :company')
      ->andWhere('r.date >= :start')
      ->andWhere('r.date <= :end')
      ->setParameter('company', $company)
      ->setParameter('start', $year.'-01-01')
      ->setParameter('end',  $year.'-12-31')
      ->addOrderBy('c.nom', 'ASC');

    return $qb->getQuery()->getResult();
  }

  public function findForCompanyByYearAndAnalytique($company, $year, $analytique){

    $qb = $this->createQueryBuilder('r')
      ->innerJoin('r.opportunite', 'o')
      ->innerJoin('o.compte', 'c')
      ->where('c.company = :company')
      ->andWhere('r.date >= :start')
      ->andWhere('r.date <= :end')
      ->andWhere('o.analytique = :analytique')
      ->setParameter('company', $company)
      ->setParameter('start', $year.'-01-01')
      ->setParameter('end',  $year.'-12-31')
      ->setParameter('analytique', $analytique)
      ->addOrderBy('c.nom', 'ASC');

    return $qb->getQuery()->getResult();
  }

  public function findForCompanyByYearAndAnalytiqueAndPublicOrPrive($company, $year, $analytique, $publicOrPrive){

    $qb = $this->createQueryBuilder('r')
      ->innerJoin('r.opportunite', 'o')
      ->innerJoin('o.compte', 'c')
      ->where('c.company = :company')
      ->andWhere('r.date >= :start')
      ->andWhere('r.date <= :end')
      ->andWhere('o.analytique = :analytique')
      ->andWhere('o.priveOrPublic = :publicOrPrive')
      ->setParameter('company', $company)
      ->setParameter('start', $year.'-01-01')
      ->setParameter('end',  $year.'-12-31')
      ->setParameter('analytique', $analytique)
      ->setParameter('publicOrPrive', $publicOrPrive)
      ->addOrderBy('c.nom', 'ASC');

    return $qb->getQuery()->getResult();
  }
}
