<?php

namespace AppBundle\Entity\NDF;

use Doctrine\ORM\EntityRepository;

/**
 * NoteFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteFraisRepository extends EntityRepository
{
	public function findForList($company, $length, $start, $orderBy, $dir, $search, $rapprochement = '', $dateRange = '' ){

		$qb = $this->createQueryBuilder('n')
		->select('n.id',  "CONCAT( CONCAT(u.firstname, ' '),  u.lastname) as nom" , 'n.month', 'n.year', 'n.etat')
		->leftJoin('AppBundle\Entity\Compta\CompteComptable', 'c', 'WITH', 'c.id = n.compteComptable')
		->leftJoin('AppBundle\Entity\User', 'u', 'WITH', 'u.id = n.user')
		->where('c.company = :company')
		->setParameter('company', $company);

		if( is_array($dateRange) ){
			$qb
				->andWhere('n.year >= :anneeDebut')
				->andWhere('n.month >= :moisDebut')
				->setParameter('anneeDebut',\DateTime::createFromFormat('D M d Y H:i:s e+', $dateRange['start'])->format('Y'))
				->setParameter('moisDebut',\DateTime::createFromFormat('D M d Y H:i:s e+', $dateRange['start'])->format('n'))
				->andWhere('n.year <= :anneeFin')
				->andWhere('n.month <= :moisFin')
				->setParameter('anneeFin', \DateTime::createFromFormat('D M d Y H:i:s e+', $dateRange['end'])->format('Y'))
				->setParameter('moisFin', \DateTime::createFromFormat('D M d Y H:i:s e+', $dateRange['end'])->format('n'));
		}
		if( $rapprochement == 'RAPPROCHE') {
			$qb
				->andWhere('n.etat = :rapproche')
				->setParameter('rapproche', $rapprochement);
		}
		else if ($rapprochement == 'ENREGISTRE') {
			$qb
				->andWhere('n.etat = :rapproche')
				->setParameter('rapproche', $rapprochement);
		}


		$qb->setMaxResults($length)
		->setFirstResult($start);

		return $qb->getQuery()->getResult();
	}

	public function countForList($company, $search,$rapprochement = '', $dateRange = ''){
		$qb = $this->createQueryBuilder('n')
		->select('COUNT(n)')
		->leftJoin('AppBundle\Entity\Compta\CompteComptable', 'c', 'WITH', 'c.id = n.compteComptable')
		->where('c.company = :company')
		->setParameter('company', $company);

		if( is_array($dateRange) ){
			$qb
				->andWhere('n.year >= :anneeDebut')
				->andWhere('n.month >= :moisDebut')
				->setParameter('anneeDebut',\DateTime::createFromFormat('D M d Y H:i:s e+', $dateRange['start'])->format('Y'))
				->setParameter('moisDebut', \DateTime::createFromFormat('D M d Y H:i:s e+', $dateRange['start'])->format('n'))
				->andWhere('n.year <= :anneeFin')
				->andWhere('n.month <= :moisFin')
				->setParameter('anneeFin', \DateTime::createFromFormat('D M d Y H:i:s e+', $dateRange['end'])->format('Y'))
				->setParameter('moisFin', \DateTime::createFromFormat('D M d Y H:i:s e+', $dateRange['start'])->format('n'));
		}
		if( $rapprochement != ''){
			if($rapprochement = 'rapproche'){
				$qb
					->andWhere('n.etat = :rapproche')
					->setParameter('rapproche', $rapprochement);
			}
			else{
				$qb
					->andWhere('n.etat = :rapproche')
					->setParameter('rapproche', $rapprochement);
			}
		}


		return $qb->getQuery()->getSingleScalarResult();
	}

	public function count($company){
		$qb = $this->createQueryBuilder('n')
		->select('COUNT(n)')
		->leftJoin('AppBundle\Entity\Compta\CompteComptable', 'c', 'WITH', 'c.id = n.compteComptable')
		->where('c.company = :company')
		->setParameter('company', $company);

		return $qb->getQuery()->getSingleScalarResult();
	}

	public function findForCompany($company){
		$qb = $this->createQueryBuilder('n')
		->leftJoin('AppBundle\Entity\Compta\CompteComptable', 'c', 'WITH', 'c.id = n.compteComptable')
		->where('c.company = :company')
		->setParameter('company', $company);

		return $qb->getQuery()->getResult();
	}

}
