<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends EntityRepository
{
	public function findParametres($module){
		$result = $this->createQueryBuilder('s')
		->select('DISTINCT s.parametre')
		->where('s.module = :module')
		->setParameter('module', $module)
		->getQuery()
		->getResult();
	
		return $result;
	}
	
	public function findValeurs($module, $parametre, $company){
		$result = $this->createQueryBuilder('s')
		->where('s.module = :module')
		->andWhere('s.parametre = :parametre')
		->andWhere('s.company = :company')
		->setParameter('module', $module)
		->setParameter('parametre', $parametre)
		->setParameter('company', $company)
		->getQuery()
		->getResult();
	
		return $result;
	}
}
