<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SettingsActivationOutilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsActivationOutilRepository extends EntityRepository
{
	public function countByOutil($outil){
		$result = $this->createQueryBuilder('s')
		->select('COUNT(s)')
		->where('s.outil = :outil')
		->setParameter('outil', $outil)
		->getQuery()
		->getSingleScalarResult();
	
		return $result;
	}
	
	public function countByNbOutil($nb){
		$result = $this->createQueryBuilder('s')
		->groupBy('s.company')
		->having('COUNT(s) = :nb')
		->setParameter('nb', $nb)
		->getQuery()
		->getResult();
		
		return $result;
		
	}
}
