<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function count(){
		$result = $this->createQueryBuilder('u')
		->select('COUNT(u)')
		->getQuery()
		->getSingleScalarResult();
	
		return $result;
	}
	
	public function countValides(){
	
		$result = $this->createQueryBuilder('u')
		->select('COUNT(u)')
		->where('u.enabled = :enabled')
		->setParameter('enabled', true)
		->getQuery()
		->getSingleScalarResult();
	
		return $result;
	}
	
	public function countActifs(){
	
		$result = $this->createQueryBuilder('u')
		->select('COUNT(u)')
		->where('u.lastLogin >= :lastLogin')
		->setParameter('lastLogin', date('Y-m-d', strtotime('-7 days')))
		->getQuery()
		->getSingleScalarResult();
	
		return $result;
	}
}
